rabbitmq:
  image: rabbitmq

d0:
  build: ./dict
  volumes:
   - ./dict:/code
  links:
   - rabbitmq
  command: ./run.sh dict:DictService0

d1:
  build: ./dict
  volumes:
   - ./dict:/code
  links:
   - rabbitmq
  command: ./run.sh dict:DictService1

d2:
  build: ./dict
  volumes:
   - ./dict:/code
  links:
   - rabbitmq
  command: ./run.sh dict:DictService2

putter:
  build: ./putter
  volumes:
   - ./putter:/code
  links:
   - rabbitmq
